<?php

namespace Database\Seeders;

use App\Models\Pupil;
use App\Models\Role;
use App\Models\School;
use App\Models\TeacherAssignment;
use App\Models\User;
use App\Models\UserPin;
use App\Models\UserSchoolRole;
use Illuminate\Database\Seeder;

class SampleDataSeeder extends Seeder
{
    public function run(): void
    {
        // ── Roles (upsert — safe to re-run) ──────────────────────────────────
        $roleSuperAdmin = Role::firstOrCreate(['slug' => 'super_admin'], ['name' => 'Super Admin']);
        $roleAdmin      = Role::firstOrCreate(['slug' => 'school_admin'], ['name' => 'School Admin']);
        $roleTeacher    = Role::firstOrCreate(['slug' => 'teacher'],      ['name' => 'Teacher']);

        // ── Schools ───────────────────────────────────────────────────────────
        // School model auto-generates slug + code in booted()
        $school1 = School::create([
            'name'         => 'Greenwood Academy',
            'school_type'  => 'secondary',
            'region'       => 'London',
            'gender'       => 'mixed',
            'address'      => '12 Greenwood Lane, London, E1 6RF',
            'school_years' => ['Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11'],
            'is_active'    => true,
        ]);

        $school2 = School::create([
            'name'         => 'Riverside High',
            'school_type'  => 'secondary',
            'region'       => 'Manchester',
            'gender'       => 'mixed',
            'address'      => '45 River Street, Manchester, M1 2AB',
            'school_years' => ['Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11'],
            'is_active'    => true,
        ]);

        $school3 = School::create([
            'name'         => "St. Mary's College",
            'school_type'  => 'sixth_form',
            'region'       => 'Birmingham',
            'gender'       => 'mixed',
            'address'      => '8 Cathedral Road, Birmingham, B1 3PQ',
            'school_years' => ['Year 12', 'Year 13'],
            'is_active'    => true,
        ]);

        // ── User 1: Teacher at School 1 (Greenwood Academy) ──────────────────
        // Password + PIN casts are 'hashed' on the models — pass plain text.
        $teacher = User::create([
            'name'      => 'Sarah Jones',
            'email'     => 'sarah.jones@greenwood.edu',
            'password'  => 'Teacher@1234',
            'is_active' => true,
        ]);
        UserPin::create(['user_id' => $teacher->id, 'pin' => '112233']);
        UserSchoolRole::create([
            'user_id'     => $teacher->id,
            'school_id'   => $school1->id,
            'role_id'     => $roleTeacher->id,
            'is_active'   => true,
            'assigned_at' => now(),
        ]);
        TeacherAssignment::create([
            'user_id'     => $teacher->id,
            'school_id'   => $school1->id,
            'school_year' => 'Year 9',
            'class_name'  => '9A',
        ]);

        // ── Pupil: assigned to Sarah at School 1 ─────────────────────────────
        // pupil_id is auto-generated by Pupil::booted(); pin cast is 'hashed'.
        $pupil = Pupil::create([
            'school_id'           => $school1->id,
            'first_name'          => 'Oliver',
            'last_name'           => 'Davies',
            'date_of_birth'       => '2011-03-15',
            'year_group'          => 'Year 9',
            'class_name'          => '9A',
            'teacher_id'          => $teacher->id,
            'pin'                 => '246810',
            'include_in_averages' => true,
            'sen'                 => 'none',
            'is_active'           => true,
        ]);

        // ── User 2: Admin at School 1 AND School 2 ───────────────────────────
        $adminTwo = User::create([
            'name'      => 'Michael Chen',
            'email'     => 'michael.chen@admin.edu',
            'password'  => 'Admin@1234',
            'is_active' => true,
        ]);
        UserPin::create(['user_id' => $adminTwo->id, 'pin' => '445566']);
        foreach ([$school1, $school2] as $school) {
            UserSchoolRole::create([
                'user_id'     => $adminTwo->id,
                'school_id'   => $school->id,
                'role_id'     => $roleAdmin->id,
                'is_active'   => true,
                'assigned_at' => now(),
            ]);
        }

        // ── User 3: Teacher (non-admin) at School 1 AND School 2 ─────────────
        $teacherTwo = User::create([
            'name'      => 'Emma Wilson',
            'email'     => 'emma.wilson@schools.edu',
            'password'  => 'Teacher@1234',
            'is_active' => true,
        ]);
        UserPin::create(['user_id' => $teacherTwo->id, 'pin' => '778899']);
        foreach ([$school1, $school2] as $school) {
            UserSchoolRole::create([
                'user_id'     => $teacherTwo->id,
                'school_id'   => $school->id,
                'role_id'     => $roleTeacher->id,
                'is_active'   => true,
                'assigned_at' => now(),
            ]);
        }
        TeacherAssignment::insert([
            [
                'user_id'     => $teacherTwo->id,
                'school_id'   => $school1->id,
                'school_year' => 'Year 8',
                'class_name'  => '8B',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'user_id'     => $teacherTwo->id,
                'school_id'   => $school2->id,
                'school_year' => 'Year 8',
                'class_name'  => '8C',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ]);

        // ── User 4: Admin at School 1, Teacher at School 3 (mixed roles) ─────
        $mixedUser = User::create([
            'name'      => 'David Brown',
            'email'     => 'david.brown@schools.edu',
            'password'  => 'Mixed@1234',
            'is_active' => true,
        ]);
        UserPin::create(['user_id' => $mixedUser->id, 'pin' => '998877']);
        UserSchoolRole::create([
            'user_id'     => $mixedUser->id,
            'school_id'   => $school1->id,
            'role_id'     => $roleAdmin->id,
            'is_active'   => true,
            'assigned_at' => now(),
        ]);
        UserSchoolRole::create([
            'user_id'     => $mixedUser->id,
            'school_id'   => $school3->id,
            'role_id'     => $roleTeacher->id,
            'is_active'   => true,
            'assigned_at' => now(),
        ]);
        TeacherAssignment::create([
            'user_id'     => $mixedUser->id,
            'school_id'   => $school3->id,
            'school_year' => 'Year 12',
            'class_name'  => '12A',
        ]);

        // ── Console output ────────────────────────────────────────────────────
        $this->command->info('');
        $this->command->info('══════════════════════════════════════════════════════════════');
        $this->command->info('  SAMPLE DATA SEEDED SUCCESSFULLY');
        $this->command->info('══════════════════════════════════════════════════════════════');
        $this->command->info('');
        $this->command->info('  SCHOOLS');
        $this->command->info('  -------');
        $this->command->info("  1. Greenwood Academy   (ID: {$school1->id}, Code: {$school1->code})");
        $this->command->info("  2. Riverside High      (ID: {$school2->id}, Code: {$school2->code})");
        $this->command->info("  3. St. Mary's College  (ID: {$school3->id}, Code: {$school3->code})");
        $this->command->info('');
        $this->command->info('  USERS (two-step login: /login)');
        $this->command->info('  ------------------------------');
        $this->command->info('  Sarah Jones (Teacher @ Greenwood Academy — Year 9, Class 9A)');
        $this->command->info('    Email:    sarah.jones@greenwood.edu');
        $this->command->info('    Password: Teacher@1234');
        $this->command->info('    PIN:      112233');
        $this->command->info('');
        $this->command->info('  Michael Chen (Admin @ Greenwood Academy + Riverside High)');
        $this->command->info('    Email:    michael.chen@admin.edu');
        $this->command->info('    Password: Admin@1234');
        $this->command->info('    PIN:      445566');
        $this->command->info('');
        $this->command->info("  Emma Wilson (Teacher @ Greenwood Academy [8B] + Riverside High [8C])");
        $this->command->info('    Email:    emma.wilson@schools.edu');
        $this->command->info('    Password: Teacher@1234');
        $this->command->info('    PIN:      778899');
        $this->command->info('');
        $this->command->info("  David Brown (Admin @ Greenwood Academy | Teacher @ St. Mary's [12A])");
        $this->command->info('    Email:    david.brown@schools.edu');
        $this->command->info('    Password: Mixed@1234');
        $this->command->info('    PIN:      998877');
        $this->command->info('');
        $this->command->info('  PUPIL (login: /pupil/login)');
        $this->command->info('  --------------------------');
        $this->command->info('  Oliver Davies (Year 9 / 9A @ Greenwood Academy, teacher: Sarah Jones)');
        $this->command->info("    Pupil ID: {$pupil->pupil_id}");
        $this->command->info('    PIN:      246810');
        $this->command->info('');
        $this->command->info('══════════════════════════════════════════════════════════════');
        $this->command->info('');
    }
}
